/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DiscoveryRouteImport } from './routes/discovery'
import { Route as CreateGroupRouteImport } from './routes/create-group'
import { Route as CreateChannelRouteImport } from './routes/create-channel'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsPrivacyRouteImport } from './routes/settings/privacy'
import { Route as SettingsNetworkRouteImport } from './routes/settings/network'
import { Route as SettingsDiscoveryRouteImport } from './routes/settings/discovery'
import { Route as SettingsConnectRouteImport } from './routes/settings/connect'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as GroupsGroupIdRouteImport } from './routes/groups.$groupId'
import { Route as ContactInfoAddressRouteImport } from './routes/contact-info.$address'
import { Route as ChatAddressRouteImport } from './routes/chat/$address'
import { Route as ChannelsChannelIdRouteImport } from './routes/channels.$channelId'
import { Route as ChannelInfoChannelIdRouteImport } from './routes/channel-info.$channelId'

const GroupInfoGroupIdLazyRouteImport = createFileRoute(
  '/group-info/$groupId',
)()

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryRoute = DiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/discovery.lazy').then((d) => d.Route))
const CreateGroupRoute = CreateGroupRouteImport.update({
  id: '/create-group',
  path: '/create-group',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateChannelRoute = CreateChannelRouteImport.update({
  id: '/create-channel',
  path: '/create-channel',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const GroupInfoGroupIdLazyRoute = GroupInfoGroupIdLazyRouteImport.update({
  id: '/group-info/$groupId',
  path: '/group-info/$groupId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/group-info.$groupId.lazy').then((d) => d.Route),
)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPrivacyRoute = SettingsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNetworkRoute = SettingsNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDiscoveryRoute = SettingsDiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectRoute = SettingsConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/groups.$groupId.lazy').then((d) => d.Route),
)
const ContactInfoAddressRoute = ContactInfoAddressRouteImport.update({
  id: '/contact-info/$address',
  path: '/contact-info/$address',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/contact-info.$address.lazy').then((d) => d.Route),
)
const ChatAddressRoute = ChatAddressRouteImport.update({
  id: '/chat/$address',
  path: '/chat/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsChannelIdRoute = ChannelsChannelIdRouteImport.update({
  id: '/channels/$channelId',
  path: '/channels/$channelId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/channels.$channelId.lazy').then((d) => d.Route),
)
const ChannelInfoChannelIdRoute = ChannelInfoChannelIdRouteImport.update({
  id: '/channel-info/$channelId',
  path: '/channel-info/$channelId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/channel-info.$channelId.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/create-channel': typeof CreateChannelRoute
  '/create-group': typeof CreateGroupRoute
  '/discovery': typeof DiscoveryRoute
  '/help': typeof HelpRoute
  '/settings': typeof SettingsRouteWithChildren
  '/channel-info/$channelId': typeof ChannelInfoChannelIdRoute
  '/channels/$channelId': typeof ChannelsChannelIdRoute
  '/chat/$address': typeof ChatAddressRoute
  '/contact-info/$address': typeof ContactInfoAddressRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/connect': typeof SettingsConnectRoute
  '/settings/discovery': typeof SettingsDiscoveryRoute
  '/settings/network': typeof SettingsNetworkRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/group-info/$groupId': typeof GroupInfoGroupIdLazyRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/create-channel': typeof CreateChannelRoute
  '/create-group': typeof CreateGroupRoute
  '/discovery': typeof DiscoveryRoute
  '/help': typeof HelpRoute
  '/channel-info/$channelId': typeof ChannelInfoChannelIdRoute
  '/channels/$channelId': typeof ChannelsChannelIdRoute
  '/chat/$address': typeof ChatAddressRoute
  '/contact-info/$address': typeof ContactInfoAddressRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/connect': typeof SettingsConnectRoute
  '/settings/discovery': typeof SettingsDiscoveryRoute
  '/settings/network': typeof SettingsNetworkRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/group-info/$groupId': typeof GroupInfoGroupIdLazyRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/create-channel': typeof CreateChannelRoute
  '/create-group': typeof CreateGroupRoute
  '/discovery': typeof DiscoveryRoute
  '/help': typeof HelpRoute
  '/settings': typeof SettingsRouteWithChildren
  '/channel-info/$channelId': typeof ChannelInfoChannelIdRoute
  '/channels/$channelId': typeof ChannelsChannelIdRoute
  '/chat/$address': typeof ChatAddressRoute
  '/contact-info/$address': typeof ContactInfoAddressRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/connect': typeof SettingsConnectRoute
  '/settings/discovery': typeof SettingsDiscoveryRoute
  '/settings/network': typeof SettingsNetworkRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/group-info/$groupId': typeof GroupInfoGroupIdLazyRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contacts'
    | '/create-channel'
    | '/create-group'
    | '/discovery'
    | '/help'
    | '/settings'
    | '/channel-info/$channelId'
    | '/channels/$channelId'
    | '/chat/$address'
    | '/contact-info/$address'
    | '/groups/$groupId'
    | '/settings/appearance'
    | '/settings/connect'
    | '/settings/discovery'
    | '/settings/network'
    | '/settings/privacy'
    | '/settings/profile'
    | '/group-info/$groupId'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contacts'
    | '/create-channel'
    | '/create-group'
    | '/discovery'
    | '/help'
    | '/channel-info/$channelId'
    | '/channels/$channelId'
    | '/chat/$address'
    | '/contact-info/$address'
    | '/groups/$groupId'
    | '/settings/appearance'
    | '/settings/connect'
    | '/settings/discovery'
    | '/settings/network'
    | '/settings/privacy'
    | '/settings/profile'
    | '/group-info/$groupId'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contacts'
    | '/create-channel'
    | '/create-group'
    | '/discovery'
    | '/help'
    | '/settings'
    | '/channel-info/$channelId'
    | '/channels/$channelId'
    | '/chat/$address'
    | '/contact-info/$address'
    | '/groups/$groupId'
    | '/settings/appearance'
    | '/settings/connect'
    | '/settings/discovery'
    | '/settings/network'
    | '/settings/privacy'
    | '/settings/profile'
    | '/group-info/$groupId'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactsRoute: typeof ContactsRoute
  CreateChannelRoute: typeof CreateChannelRoute
  CreateGroupRoute: typeof CreateGroupRoute
  DiscoveryRoute: typeof DiscoveryRoute
  HelpRoute: typeof HelpRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  ChannelInfoChannelIdRoute: typeof ChannelInfoChannelIdRoute
  ChannelsChannelIdRoute: typeof ChannelsChannelIdRoute
  ChatAddressRoute: typeof ChatAddressRoute
  ContactInfoAddressRoute: typeof ContactInfoAddressRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRoute
  GroupInfoGroupIdLazyRoute: typeof GroupInfoGroupIdLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery': {
      id: '/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof DiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-group': {
      id: '/create-group'
      path: '/create-group'
      fullPath: '/create-group'
      preLoaderRoute: typeof CreateGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-channel': {
      id: '/create-channel'
      path: '/create-channel'
      fullPath: '/create-channel'
      preLoaderRoute: typeof CreateChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/group-info/$groupId': {
      id: '/group-info/$groupId'
      path: '/group-info/$groupId'
      fullPath: '/group-info/$groupId'
      preLoaderRoute: typeof GroupInfoGroupIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/network': {
      id: '/settings/network'
      path: '/network'
      fullPath: '/settings/network'
      preLoaderRoute: typeof SettingsNetworkRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/discovery': {
      id: '/settings/discovery'
      path: '/discovery'
      fullPath: '/settings/discovery'
      preLoaderRoute: typeof SettingsDiscoveryRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connect': {
      id: '/settings/connect'
      path: '/connect'
      fullPath: '/settings/connect'
      preLoaderRoute: typeof SettingsConnectRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-info/$address': {
      id: '/contact-info/$address'
      path: '/contact-info/$address'
      fullPath: '/contact-info/$address'
      preLoaderRoute: typeof ContactInfoAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$address': {
      id: '/chat/$address'
      path: '/chat/$address'
      fullPath: '/chat/$address'
      preLoaderRoute: typeof ChatAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels/$channelId': {
      id: '/channels/$channelId'
      path: '/channels/$channelId'
      fullPath: '/channels/$channelId'
      preLoaderRoute: typeof ChannelsChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel-info/$channelId': {
      id: '/channel-info/$channelId'
      path: '/channel-info/$channelId'
      fullPath: '/channel-info/$channelId'
      preLoaderRoute: typeof ChannelInfoChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsConnectRoute: typeof SettingsConnectRoute
  SettingsDiscoveryRoute: typeof SettingsDiscoveryRoute
  SettingsNetworkRoute: typeof SettingsNetworkRoute
  SettingsPrivacyRoute: typeof SettingsPrivacyRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsConnectRoute: SettingsConnectRoute,
  SettingsDiscoveryRoute: SettingsDiscoveryRoute,
  SettingsNetworkRoute: SettingsNetworkRoute,
  SettingsPrivacyRoute: SettingsPrivacyRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactsRoute: ContactsRoute,
  CreateChannelRoute: CreateChannelRoute,
  CreateGroupRoute: CreateGroupRoute,
  DiscoveryRoute: DiscoveryRoute,
  HelpRoute: HelpRoute,
  SettingsRoute: SettingsRouteWithChildren,
  ChannelInfoChannelIdRoute: ChannelInfoChannelIdRoute,
  ChannelsChannelIdRoute: ChannelsChannelIdRoute,
  ChatAddressRoute: ChatAddressRoute,
  ContactInfoAddressRoute: ContactInfoAddressRoute,
  GroupsGroupIdRoute: GroupsGroupIdRoute,
  GroupInfoGroupIdLazyRoute: GroupInfoGroupIdLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
