/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as InfoRouteImport } from './routes/info'
import { Route as DiscoveryRouteImport } from './routes/discovery'
import { Route as CreateGroupRouteImport } from './routes/create-group'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupsGroupIdRouteImport } from './routes/groups.$groupId'
import { Route as ContactInfoAddressRouteImport } from './routes/contact-info.$address'
import { Route as ChatAddressRouteImport } from './routes/chat/$address'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoRoute = InfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryRoute = DiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateGroupRoute = CreateGroupRouteImport.update({
  id: '/create-group',
  path: '/create-group',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactInfoAddressRoute = ContactInfoAddressRouteImport.update({
  id: '/contact-info/$address',
  path: '/contact-info/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatAddressRoute = ChatAddressRouteImport.update({
  id: '/chat/$address',
  path: '/chat/$address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/create-group': typeof CreateGroupRoute
  '/discovery': typeof DiscoveryRoute
  '/info': typeof InfoRoute
  '/settings': typeof SettingsRoute
  '/chat/$address': typeof ChatAddressRoute
  '/contact-info/$address': typeof ContactInfoAddressRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/create-group': typeof CreateGroupRoute
  '/discovery': typeof DiscoveryRoute
  '/info': typeof InfoRoute
  '/settings': typeof SettingsRoute
  '/chat/$address': typeof ChatAddressRoute
  '/contact-info/$address': typeof ContactInfoAddressRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/create-group': typeof CreateGroupRoute
  '/discovery': typeof DiscoveryRoute
  '/info': typeof InfoRoute
  '/settings': typeof SettingsRoute
  '/chat/$address': typeof ChatAddressRoute
  '/contact-info/$address': typeof ContactInfoAddressRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacts'
    | '/create-group'
    | '/discovery'
    | '/info'
    | '/settings'
    | '/chat/$address'
    | '/contact-info/$address'
    | '/groups/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacts'
    | '/create-group'
    | '/discovery'
    | '/info'
    | '/settings'
    | '/chat/$address'
    | '/contact-info/$address'
    | '/groups/$groupId'
  id:
    | '__root__'
    | '/'
    | '/contacts'
    | '/create-group'
    | '/discovery'
    | '/info'
    | '/settings'
    | '/chat/$address'
    | '/contact-info/$address'
    | '/groups/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactsRoute: typeof ContactsRoute
  CreateGroupRoute: typeof CreateGroupRoute
  DiscoveryRoute: typeof DiscoveryRoute
  InfoRoute: typeof InfoRoute
  SettingsRoute: typeof SettingsRoute
  ChatAddressRoute: typeof ChatAddressRoute
  ContactInfoAddressRoute: typeof ContactInfoAddressRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info': {
      id: '/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof InfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery': {
      id: '/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof DiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-group': {
      id: '/create-group'
      path: '/create-group'
      fullPath: '/create-group'
      preLoaderRoute: typeof CreateGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-info/$address': {
      id: '/contact-info/$address'
      path: '/contact-info/$address'
      fullPath: '/contact-info/$address'
      preLoaderRoute: typeof ContactInfoAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$address': {
      id: '/chat/$address'
      path: '/chat/$address'
      fullPath: '/chat/$address'
      preLoaderRoute: typeof ChatAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactsRoute: ContactsRoute,
  CreateGroupRoute: CreateGroupRoute,
  DiscoveryRoute: DiscoveryRoute,
  InfoRoute: InfoRoute,
  SettingsRoute: SettingsRoute,
  ChatAddressRoute: ChatAddressRoute,
  ContactInfoAddressRoute: ContactInfoAddressRoute,
  GroupsGroupIdRoute: GroupsGroupIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
